export const data = [
  {
    type: "double_radio",
    title: "单选题1",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 0,
  },
  {
    type: "single_choice_question",
    title: "单选题2",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 2,
  },
  {
    type: "single_choice_question",
    title: "单选题3",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 3,
  },
  {
    type: "single_choice_question",
    title: "单选题4",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 0,
  },
  {
    type: "single_choice_question",
    title: "单选题5",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 1,
  },
  {
    type: "single_choice_question",
    title: "单选题6",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 2,
  },
  {
    type: "single_choice_question",
    title: "单选题7",
    options: ["选项1", "选项2", "选项3", "选项4"],
    rightAnswer: 3,
  },
  {
    type: "judgment_question",
    title: "判断题1",
    options: ["选项1", "选项2"],
    rightAnswer: 1,
  },
  {
    type: "judgment_question",
    title: "判断题2",
    options: ["选项1", "选项2"],
    rightAnswer: 1,
  },
  {
    type: "judgment_question",
    title: "判断题3",
    options: ["选项1", "选项2"],
    rightAnswer: 1,
  },
  {
    type: "multiple_choice_question",
    title: "多选题1",
    options: ["选项1", "选项2", "选项3", "选项4", "选项5"],
    rightAnswer: [0, 1, 2],
  },
  {
    type: "multiple_choice_question",
    title: "多选题2",
    options: ["选项1", "选项2", "选项3", "选项4", "选项5"],
    rightAnswer: [0, 1, 2],
  },
  {
    type: "multiple_choice_question",
    title: "多选题3",
    options: ["选项1", "选项2", "选项3", "选项4", "选项5"],
    rightAnswer: [0, 1, 2],
  },
];
